webtalk_init -webtalk_dir /home/bcluzel/Documents/SEE/2A/Concept_hard_proc_4_intruct/Uc4Instruction/VivadoProject/VivadoProject.sim/sim_1/behav/xsim/xsim.dir/nregister_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 12 17:28:58 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2c65b583-4179-4a17-b235-7126057033c1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "611ada42b5e641b3a4f153e4f00e047c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1736.401 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "114580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1896145405 -regid "" -xml /home/bcluzel/Documents/SEE/2A/Concept_hard_proc_4_intruct/Uc4Instruction/VivadoProject/VivadoProject.sim/sim_1/behav/xsim/xsim.dir/nregister_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/bcluzel/Documents/SEE/2A/Concept_hard_proc_4_intruct/Uc4Instruction/VivadoProject/VivadoProject.sim/sim_1/behav/xsim/xsim.dir/nregister_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/bcluzel/Documents/SEE/2A/Concept_hard_proc_4_intruct/Uc4Instruction/VivadoProject/VivadoProject.sim/sim_1/behav/xsim/xsim.dir/nregister_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
